# -*- coding: utf-8 -*-
"""dcgan_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5ycqmgR3ppmKLyfD0YRPw86RNGPy706
"""

import os

import os
import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras import layers

DATA_DIR = '/mnt/c/123/data/images'
IMG_SIZE = 64
MAX_IMAGES = 5000

def load_and_preprocess_images(path):
    images = []
    for img_name in os.listdir(path)[:MAX_IMAGES]:
        img = cv2.imread(os.path.join(path, img_name))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = (img.astype(np.float32) / 127.5) - 1.0
        images.append(img)
    return np.array(images)

images = load_and_preprocess_images(DATA_DIR)
print(images.shape, images.min(), images.max())

BATCH_SIZE = 64

dataset = tf.data.Dataset.from_tensor_slices(images)
dataset = dataset.shuffle(1000).batch(BATCH_SIZE)

def build_generator():
    model = tf.keras.Sequential([
        layers.Dense(8*8*256, use_bias=False, input_shape=(100,)),
        layers.BatchNormalization(),
        layers.ReLU(),
        layers.Reshape((8, 8, 256)),
        layers.Conv2DTranspose(128, 4, strides=2, padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.ReLU(),
        layers.Conv2DTranspose(64, 4, strides=2, padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.ReLU(),
        layers.Conv2DTranspose(3, 4, strides=2, padding='same', activation='tanh')
    ])
    return model

generator = build_generator()
generator.summary()

def build_discriminator():
    model = tf.keras.Sequential([
        layers.Conv2D(64, 4, strides=2, padding='same', input_shape=(64,64,3)),
        layers.LeakyReLU(0.2),
        layers.Dropout(0.3),
        layers.Conv2D(128, 4, strides=2, padding='same'),
        layers.LeakyReLU(0.2),
        layers.Dropout(0.3),
        layers.Flatten(),
        layers.Dense(1, activation='sigmoid')
    ])
    return model

discriminator = build_discriminator()
discriminator.summary()

cross_entropy = tf.keras.losses.BinaryCrossentropy()

def generator_loss(fake_output):
    return cross_entropy(tf.ones_like(fake_output), fake_output)

def discriminator_loss(real_output, fake_output):
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    return real_loss + fake_loss

gen_optimizer = tf.keras.optimizers.Adam(1e-4, beta_1=0.5)
disc_optimizer = tf.keras.optimizers.Adam(1e-4, beta_1=0.5)

@tf.function
def train_step(images):
    noise = tf.random.normal([tf.shape(images)[0], 100])

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        generated_images = generator(noise, training=True)
        real_output = discriminator(images, training=True)
        fake_output = discriminator(generated_images, training=True)

        gen_loss = generator_loss(fake_output)
        disc_loss = discriminator_loss(real_output, fake_output)

    gradients_gen = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_disc = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    gen_optimizer.apply_gradients(zip(gradients_gen, generator.trainable_variables))
    disc_optimizer.apply_gradients(zip(gradients_disc, discriminator.trainable_variables))

    return gen_loss, disc_loss

def generate_and_save_images(model, epoch, test_input):
    predictions = model(test_input, training=False)
    predictions = (predictions + 1) / 2.0
    
    plt.figure(figsize=(4,4))
    for i in range(16):
        plt.subplot(4, 4, i+1)
        plt.imshow(predictions[i])
        plt.axis('off')
    plt.suptitle(f"Epoch {epoch}")
    os.makedirs('/mnt/c/123/epochs_output', exist_ok=True)
    plt.savefig(f'/mnt/c/123/epochs_output/epoch_{epoch}.png')
    plt.close()

EPOCHS = 50
seed = tf.random.normal([16, 100])

for epoch in range(1, EPOCHS+1):
    for image_batch in dataset:
        gen_loss, disc_loss = train_step(image_batch)

    if epoch == 31:
        gen_optimizer.learning_rate.assign(5e-5)
        print("Reduced generator learning rate")

    if epoch % 5 == 0:
        print(f"Epoch {epoch} | Gen Loss: {gen_loss:.4f} | Disc Loss: {disc_loss:.4f}")
        generate_and_save_images(generator, epoch, seed)

generator.save('/mnt/c/123/dcgan_generator_epoch50.keras')
print("Generator saved successfully")

import os

SAVE_DIR = '/mnt/c/123/synthetic_images'
os.makedirs(SAVE_DIR, exist_ok=True)

num_images = 1000   # enough for augmentation
noise = tf.random.normal([num_images, 100])
synthetic_images = generator(noise, training=False)
synthetic_images = (synthetic_images + 1) / 2.0  # back to [0,1]

for i in range(num_images):
    plt.imsave(f"{SAVE_DIR}/synthetic_{i}.png", synthetic_images[i])

print("Synthetic images saved:", num_images)

import pandas as pd
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

csv_path = '/mnt/c/123/HAM10000_metadata.csv'
img_dir = '/mnt/c/123/data/images'

df = pd.read_csv(csv_path)

# Binary labels: malignant=1, benign=0
malignant = ['mel', 'bcc', 'akiec']
df['label'] = df['dx'].apply(lambda x: 1 if x in malignant else 0)

IMG_SIZE = 64
X_real, y_real = [], []

for _, row in df.iterrows():
    img_path = img_dir + '/' + row['image_id'] + '.jpg'
    if not os.path.exists(img_path):
        continue

    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img / 255.0

    X_real.append(img)
    y_real.append(row['label'])

X_real = np.array(X_real)
y_real = np.array(y_real)

print("Real images:", X_real.shape)

from tensorflow.keras.models import load_model
import tensorflow as tf

generator = load_model('/mnt/c/123/dcgan_generator_epoch50.keras')

NUM_SYNTH = len(X_real) // 2   # 50% augmentation
noise = tf.random.normal([NUM_SYNTH, 100])

X_synth = generator(noise, training=False)
X_synth = (X_synth + 1) / 2.0

# Assign labels (same distribution)
y_synth = np.random.choice([0,1], size=len(X_synth))

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

def build_classifier():
    model = Sequential([
        Conv2D(32, 3, activation='relu', input_shape=(64,64,3)),
        MaxPooling2D(),
        Conv2D(64, 3, activation='relu'),
        MaxPooling2D(),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model

X_train, X_test, y_train, y_test = train_test_split(
    X_real, y_real, test_size=0.2, random_state=42
)

model_real = build_classifier()
history_real = model_real.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

real_acc = history_real.history['val_accuracy'][-1]
print("Validation Accuracy (Real only):", real_acc)

X_aug = np.concatenate([X_real, X_synth])
y_aug = np.concatenate([y_real, y_synth])

X_train, X_test, y_train, y_test = train_test_split(
    X_aug, y_aug, test_size=0.2, random_state=42
)

model_aug = build_classifier()
history_aug = model_aug.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

aug_acc = history_aug.history['val_accuracy'][-1]
print("Validation Accuracy (Real + Synthetic):", aug_acc)

print(f"Accuracy Improvement: {(aug_acc - real_acc)*100:.2f}%")